Algoritmo "ImprimaRepitaAte10a1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Imprime sequência numérica de 1 a 10.
// Autor(a)    : Cíntia Arbeletche
// Data atual  : 19/02/2023
Var
j: inteiro
Inicio
      escreval ("Imprimindo de 1 a 10. Repita até: ")
      j<-1
      repita
            escreval (j)
            j<-j+1
      ate j>10
      escreval ("Valor do J:  ",j)
Fimalgoritmo