Algoritmo "ImprimeEquanto1a10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Cíntia Arbeletche
// Data atual  : 18/02/2023
Var
j: inteiro
Inicio
   escreval ("Imprimindo de 1 a 10 com enquanto: ")
   j<-1
   enquanto j < 11 faca
     escreval (j)
     j<-j+1
   fimenquanto
Fimalgoritmo